name: Volarodeo
summary: is a tool to manage setups for very high risk markets like crypto
description: |
  is a tool to manage setups for very high risk markets like crypto
adopt-info: Volarodeo
base: core22
grade: devel
confinement: devmode
