#!/bin/bash

TSC_COPYRIGHT="Copyright: Kaiserrundfunk.com / Jonacast 2019"
TSC_DONTEDIT="Created by Configure at compiling - do not edit this file"
TSC_TIMESTAMP=`date "+%d.%m.%Y %H:%M:%S" `
#name of the game :-)
TSC_Proj="volarodeo"
TSC_PrettyProj="Volarodeo"
TSC_LANG_DE="de"
TSC_LANG_EN="en"
#directories
TSC_Src="./src/"
TSC_Doc="./doc/"
TSC_RPMS="./rpms/"
TSC_SRPMS="./srpms/"


#version
TSC_Major="0"
TSC_Minor="1"
TSC_Release="1"
TSC_Patch="1"
TSC_Name=$TSC_Proj-$TSC_Major.$TSC_Minor.$TSC_Release-$TSC_Patch
TSC_CMK=$TSC_Src"config.mk"
TSC_H=$TSC_Src"config.h"
TSC_SNAPYAML=$TSC_Src"snapcraft.yaml"
TSC_MF=$TSC_Src"Makefile"
TSC_SPEC=$TSC_RPMS$TSC_Name".spec"
TSC_Echo=`which echo `
TSC_Echoe=`which echo `" -e"
TSC_MK=`which make `
TSC_AR=`which ar`" -rs"
TSC_CC=`which gcc`
TSC_CP=`which cp`
TSC_RM=`which rm`" -f"
TSC_MKDIR=`which mkdir`
TSC_RMDIR=`which rmdir`
TSC_RMDIRI=`which rmdir`" --ignore-fail-on-non-empty"
TSC_Libs=`pwd`"/lib"
TSC_Incl=`pwd`"/inc"

CFLAGS=`pkg-config --cflags gtk+-3.0`
GLIBFLAGS=`pkg-config --cflags glib-2.0`
GTKFLAGS=`pkg-config --libs glib-2.0 gtk+-3.0`


$TSC_MKDIR -p $TSC_Src
$TSC_MKDIR -p $TSC_Doc
$TSC_MKDIR -p $TSC_RPMS
$TSC_MKDIR -p $TSC_SRPMS

#$1 start definition line #define or empty
#$2 start remark line
#$3 start action line
#$4 assignment operator or empty
#$5 outputfile

tsc_write_env(){

    $TSC_Echoe "write" $5
    $TSC_Echoe "$2 "$TSC_COPYRIGHT > $5
    $TSC_Echoe "\n$2 $5 "$TSC_TIMESTAMP >> $5
    $TSC_Echoe "\n$2 "$TSC_DONTEDIT >> $5
    $TSC_Echoe "\n\n$2 Globals:\n" >> $5
    $TSC_Echoe $1"TSC_NAME$4"$TSC_Name >> $5
    $TSC_Echoe $1"TSC_Major$4"$TSC_Major >> $5
    $TSC_Echoe $1"TSC_Minor$4"$TSC_Major >> $5
    $TSC_Echoe $1"TSC_Release$4"$TSC_Release >> $5
    $TSC_Echoe $1"TSC_Patch$4"$TSC_Patch >> $5
    $TSC_Echo $1"TSC_Echo$4"$TSC_Echo >> $5
    $TSC_Echoe $1"TSC_Echoe$4"$TSC_Echoe >> $5
    $TSC_Echoe $1"TSC_MK$4"$TSC_MK >> $5
    $TSC_Echoe $1"TSC_CC$4"$TSC_CC >> $5
    $TSC_Echoe $1"TSC_CP$4"$TSC_CP >> $5
    $TSC_Echoe $1"TSC_RM$4"$TSC_RM >> $5
    $TSC_Echoe $1"TSC_MKDIR$4"$TSC_MKDIR >> $5
    $TSC_Echoe $1"TSC_RMDIR$4"$TSC_RMDIR >> $5
    $TSC_Echoe $1"TSC_RMDIRI$4"$TSC_RMDIRI >> $5
    $TSC_Echoe $1"TSC_AR$4"$TSC_AR >> $5
    $TSC_Echoe $1"CFLAGS$4"$CFLAGS >> $5
    $TSC_Echoe $1"GLIBFLAGS$4"$GLIBFLAGS >> $5
    $TSC_Echoe $1"GTKFLAGS$4"$GTKFLAGS >> $5
    $TSC_Echoe $1"TSC_Libs$4"$TSC_Libs >> $5
    $TSC_Echoe $1"TSC_Incl$4"$TSC_Incl >> $5
}

tsc_write_env "" "#" "" "=" $TSC_CMK
tsc_write_env "#define " "//" "" " " $TSC_H

tsc_write_spec(){

    $TSC_Echoe "write" $4
    $TSC_Echoe "$1\n$1 Spec-File ($2) for "$2"\n$1" > $4
    $TSC_Echoe "Summary: Volarodeo($2) App for Volatrading" >> $4
    $TSC_Echoe "Version: "$TSC_Major"."$TSC_Minor  >> $4
    $TSC_Echoe "Release: "$TSC_Release"-"$TSC_Patch >> $4
    $TSC_Echoe "License: MIT" >> $4
    $TSC_Echoe "Group: Applications/Productivity" >> $4
    $TSC_Echoe "Source: https://github.com/Chartwalker/Volarodeo/stable/"$TSC_Name".src.tgz" >> $4
    $TSC_Echoe "URL: https://github.com/Chartwalker/Volarodeo/stable/doc/index.html" >> $4
    $TSC_Echoe "\n%description: see manual pdf at "$TSC_Doc >> $4

}

tsc_write_spec "#" "de" $TSC_LANG_DE $TSC_SPEC

tsc_write_snap_yaml(){
    $TSC_Echoe "write" $4
    $TSC_Echoe "name: Volarodeo" > $4
    $TSC_Echoe "summary: is a tool to manage setups for very high risk markets like crypto" >> $4
    $TSC_Echoe "description: |" >> $4
    $TSC_Echoe "  is a tool to manage setups for very high risk markets like crypto" >> $4
    $TSC_Echoe "adopt-info: Volarodeo" >> $4
    $TSC_Echoe "base: core22" >> $4
    $TSC_Echoe "grade: devel" >> $4
    $TSC_Echoe "confinement: devmode" >> $4
    $TSC_Echoe "base: core22" >> $4
}

tsc_write_snap_yaml "#" "de" $TSC_LANG_DE $TSC_SNAPYAML
