# Copyright: Kaiserrundfunk.com / Jonacast 2019-2023
# Timestamp: Linux drossel x86_64 at 10.08.2023 14:15:24
# Created by Configure at compiling - do not edit this file
#
# Globals:
TSC_PRJG_FNAME=volarodeo
TSC_PRJG_MAJOR=0
TSC_PRJG_MINOR=1
TSC_PRJG_RELAESE=1
TSC_PRJG_PATCH=2
TSC_SBP_ECHO=/usr/bin/echo
TSC_SBP_ECHOE=/usr/bin/echo -e
TSC_SBP_MK=/usr/bin/make
TSC_SBP_CC=/usr/bin/gcc
TSC_SBP_CP=/usr/bin/cp
TSC_SBP_RM=/usr/bin/rm -f
TSC_SBP_MKDIR=/usr/bin/mkdir
TSC_SBP_RMDIR=/usr/bin/rmdir
TSC_SBP_RMDIRI=/usr/bin/rmdir --ignore-fail-on-non-empty
TSC_SBP_AR=/usr/bin/ar -rs
CFLAGS_GTK=-I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/wayland -I/usr/include/libxkbcommon -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread
CFLAGS_GLIB=-I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
LIBS_GTK=-lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
TSC_CDPA_INCL=/home/uwe/github/work/Volarodeo/develop/include
TSC_CDPA_LIB=/home/uwe/github/work/Volarodeo/develop/lib
